import { DEFAULT_EN } from "./content-registry-en";

// Single source of truth for every editable text on the site: the admin dashboard's
// "Conteudo" editor is generated entirely from this list (grouped by `page`), and
// `useContent()`'s t(key) falls back to defaultText() whenever the backend has no
// override for that key yet (untranslated, or never edited). English defaults live in
// content-registry-en.ts. Keep the JSX itself free of literal PT strings, everything
// should live here so there is exactly one place to look.
export interface ContentKeyDef {
  key: string;
  page: string;
  label: string;
  defaultPt: string;
  multiline?: boolean;
}

export const CONTENT_KEYS: ContentKeyDef[] = [
  // Header
  { key: "header.nav.home", page: "header", label: "Menu: Home", defaultPt: "Home" },
  { key: "header.nav.programador", page: "header", label: "Menu: Programador", defaultPt: "Programador" },
  { key: "header.nav.empreendedor", page: "header", label: "Menu: Empreendedor", defaultPt: "Empreendedor" },
  { key: "header.nav.universitario", page: "header", label: "Menu: Universitário", defaultPt: "Universitário" },
  { key: "header.nav.portfolio", page: "header", label: "Menu: Portfolio", defaultPt: "Portfolio" },
  { key: "header.nav.contato", page: "header", label: "Menu: Contato", defaultPt: "Contato" },
  { key: "header.social.title", page: "header", label: "Título da seção de redes sociais (mobile)", defaultPt: "Redes Sociais" },
  { key: "header.audio.mute", page: "header", label: "Botão: desativar som", defaultPt: "Desativar Som" },
  { key: "header.audio.unmute", page: "header", label: "Botão: ativar som", defaultPt: "Ativar Som" },

  // Home
  { key: "home.badge", page: "home", label: "Selo acima do nome", defaultPt: "⚔️ Engenheiro de Software ⚔️" },
  { key: "home.about.eyebrow", page: "home", label: "Sobre Mim: pré-título", defaultPt: "// Selo do ofício" },
  { key: "home.about.heading", page: "home", label: "Sobre Mim: título", defaultPt: "Sobre Mim" },
  {
    key: "home.about.body",
    page: "home",
    label: "Sobre Mim: texto",
    multiline: true,
    defaultPt: `Sou engenheiro de software, pesquisador em inteligência artificial e estudante de Ciência da Computação. Comecei a programar de forma independente aos 15 anos e, desde então, desenvolvo soluções que combinam engenharia, ciência e software para resolver problemas reais.

Fundei uma comunidade internacional de computação aplicada, participei da criação de produtos utilizados globalmente e desenvolvi sistemas envolvendo automação, modelagem matemática, aprendizado de máquina e engenharia de software.

Minha experiência transita entre pesquisa e desenvolvimento, transformando problemas complexos em soluções funcionais e escaláveis. Tenho interesse em desafios que envolvam inteligência artificial, automação e sistemas distribuídos, contribuindo com equipes que buscam criar produtos de alto impacto.`,
  },
  { key: "home.manifesto.eyebrow", page: "home", label: "Manifesto: pré-título", defaultPt: "// Presença em campo" },
  { key: "home.manifesto.heading", page: "home", label: "Manifesto: título", defaultPt: "Manifesto" },
  {
    key: "home.manifesto.body",
    page: "home",
    label: "Manifesto: texto",
    multiline: true,
    defaultPt: "Acredito que software existe para resolver problemas reais. Gosto de entender sistemas complexos, questionar processos e construir soluções que gerem impacto mensurável. Seja por meio de engenharia de software, automação ou inteligência artificial, meu objetivo é transformar desafios em resultados.",
  },
  { key: "home.projects.eyebrow", page: "home", label: "Projetos: pré-título", defaultPt: "// Artefatos criados" },
  { key: "home.projects.heading", page: "home", label: "Projetos: título", defaultPt: "Principais Projetos" },
  { key: "home.projects.label", page: "home", label: "Projetos: rótulo do card", defaultPt: "Projeto" },
  { key: "home.projects.plantas.title", page: "home", label: "Projeto Monitor de Plantas: nome no card", defaultPt: "Monitor de Plantas" },
  { key: "home.projects.hefesto.title", page: "home", label: "Projeto Hefesto: nome no card", defaultPt: "Hefesto" },
  { key: "home.projects.maestro.title", page: "home", label: "Projeto Maestro: nome no card", defaultPt: "Maestro" },
  { key: "home.projects.engscan.title", page: "home", label: "Projeto EngScan: nome no card", defaultPt: "EngScan" },
  { key: "home.projects.tyto.title", page: "home", label: "Projeto TYTO: nome no card", defaultPt: "TYTO" },
  { key: "home.projects.atenas.title", page: "home", label: "Projeto Atenas: nome no card", defaultPt: "Atenas" },
  { key: "home.projects.agora.title", page: "home", label: "Projeto Ágora: nome no card", defaultPt: "Ágora" },
  { key: "home.projects.plantas.description", page: "home", label: "Projeto Monitor de Plantas: descrição", multiline: true, defaultPt: "Sistema doméstico de rega automática: ESP32 + sensores + câmera monitoram as plantas e um dashboard PWA avisa no celular, tudo sem depender de nuvem." },
  { key: "home.projects.hefesto.description", page: "home", label: "Projeto Hefesto: descrição", multiline: true, defaultPt: "Assistente de IA pessoal e local-first que cita arquivo, linha e commit em toda resposta sobre meus repositórios, e coordena agentes de escrita sob aprovação humana." },
  { key: "home.projects.hefesto.highlight", page: "home", label: "Projeto Hefesto: selo", defaultPt: "🎙️ CHAT + VOZ + AGENTES" },
  { key: "home.projects.maestro.description", page: "home", label: "Projeto Maestro: descrição", multiline: true, defaultPt: "Orquestrador local de 26 agentes de IA que planejam, implementam e testam código em worktrees Git isolados, com CLI e API própria." },
  { key: "home.projects.engscan.description", page: "home", label: "Projeto EngScan: descrição", multiline: true, defaultPt: "Solução que reduz o tempo de vistorias e inspeções de meses para poucas horas." },
  { key: "home.projects.engscan.highlight", page: "home", label: "Projeto EngScan: selo", defaultPt: "🏆 1º LUGAR EM COMPETIÇÕES" },
  { key: "home.projects.tyto.description", page: "home", label: "Projeto TYTO: descrição", multiline: true, defaultPt: "Comunidade internacional de computação e ciência. Estudamos, testamos e criamos produtos com base científica usados em diversos países." },
  { key: "home.projects.tyto.highlight", page: "home", label: "Projeto TYTO: selo", defaultPt: "🏆 RECONHECIMENTO EM UNIVERSIDADES" },
  { key: "home.projects.atenas.description", page: "home", label: "Projeto Atenas: descrição", multiline: true, defaultPt: "Assistente de IA para gerenciamento de rotinas, criação de documentos automáticos para reuniões e administração da comunidade TYTO." },
  { key: "home.projects.agora.description", page: "home", label: "Projeto Ágora: descrição", multiline: true, defaultPt: "Aplicação capaz de prever a valorização de imóveis em determinadas regiões automaticamente." },
  { key: "home.skills.eyebrow", page: "home", label: "Habilidades: pré-título", defaultPt: "// Habilidades especiais" },
  { key: "home.skills.heading", page: "home", label: "Habilidades: título", defaultPt: "Habilidades Arquetípicas" },
  { key: "home.skills.item1", page: "home", label: "Habilidade 1 (use {years} para o número de anos)", defaultPt: "{years} anos de experiência com código e eletrônica" },
  { key: "home.skills.item2", page: "home", label: "Habilidade 2", defaultPt: "Boa comunicação" },
  { key: "home.skills.item3", page: "home", label: "Habilidade 3", defaultPt: "Visão ampla de negócio" },
  { key: "home.skills.item4", page: "home", label: "Habilidade 4", defaultPt: "Dedicação a entregar resultados" },
  { key: "home.skills.item5", page: "home", label: "Habilidade 5", defaultPt: "Dedicação ao time" },
  { key: "home.languages.eyebrow", page: "home", label: "Idiomas: pré-título", defaultPt: "// Comunicação & Dialetos" },
  { key: "home.languages.heading", page: "home", label: "Idiomas: título", defaultPt: "Domínio Linguístico" },
  { key: "home.languages.pt", page: "home", label: "Idioma 1", defaultPt: "Português" },
  { key: "home.languages.en", page: "home", label: "Idioma 2", defaultPt: "Inglês" },
  { key: "home.languages.ru", page: "home", label: "Idioma 3", defaultPt: "Russo" },
  { key: "home.languages.sergipanes", page: "home", label: "Idioma 4", defaultPt: "Sergipanês" },
  { key: "home.languages.altovaliriano", page: "home", label: "Idioma 5", defaultPt: "Alto Valiriano" },
  { key: "home.footer.quip", page: "home", label: "Rodapé: frase de efeito", defaultPt: '() => isHuman ? "Conecte-se pelos botões ao lado" : "erro 404: humano não encontrado"' },
  { key: "home.status.title", page: "home", label: "Card de status: título", defaultPt: "Status na TYTO" },
  { key: "home.status.version", page: "home", label: "Card de status: versão", defaultPt: "v2.0" },
  { key: "home.status.default.patente", page: "home", label: "Card de status: item padrão (patente)", defaultPt: "Patente: Senhor da Guerra" },
  { key: "home.status.default.polis", page: "home", label: "Card de status: item padrão (polis)", defaultPt: "Polis: Maringá, BR" },
  { key: "home.status.default.esquadrao", page: "home", label: "Card de status: item padrão (esquadrão)", defaultPt: "Esquadrão: EngScan" },
  { key: "home.status.default.cargo", page: "home", label: "Card de status: item padrão (cargo)", defaultPt: "Cargo: Rex, Conselheiro e Tribuno" },

  // Programador
  { key: "programador.title", page: "programador", label: "Título da página", defaultPt: "Engenheiro de Software" },
  {
    key: "programador.intro",
    page: "programador",
    label: "Texto de introdução",
    multiline: true,
    defaultPt: `Meu rumo em tecnologia começou em um ambiente naturalmente voltado à experimentação. Cresci cercado por eletrônica, programação e jogos digitais, e queria entender como cada coisa funcionava por dentro.

No final do ensino médio, retomei esse interesse de forma mais estruturada, estudando programação, estruturas de dados, bancos de dados e desenvolvimento de software. Um dos primeiros projetos que desenvolvi foi uma assistente virtual utilizando Java e Python, criada para auxiliar meus estudos, organizar informações e facilitar a memorização de conteúdos acadêmicos.

Desde então, mantenho uma abordagem de engenharia orientada a problemas: identificar uma necessidade, compreender o contexto e construir ferramentas que gerem valor. Durante minha graduação na UFS, continuei desenvolvendo aplicações para automatizar tarefas, explorar novas tecnologias e resolver desafios reais para mim e para pessoas próximas.`,
  },
  { key: "programador.skills.heading", page: "programador", label: "Habilidades: título", defaultPt: "Habilidades Técnicas" },
  { key: "programador.skills.frontend.title", page: "programador", label: "Habilidade Front-end: título", defaultPt: "Front-end" },
  { key: "programador.skills.frontend.description", page: "programador", label: "Habilidade Front-end: descrição", defaultPt: "Design e desenvolvimento de interfaces orientadas a UI e UX." },
  { key: "programador.skills.backend.title", page: "programador", label: "Habilidade Back-end: título", defaultPt: "Back-end" },
  { key: "programador.skills.backend.description", page: "programador", label: "Habilidade Back-end: descrição", defaultPt: "Foco em otimizar recursos e escalabilidade, avaliando a viabilidade de cada processo e o melhor trade-off para cada operação." },
  { key: "programador.skills.web.title", page: "programador", label: "Habilidade Web: título", defaultPt: "Outras Tecnologias Web" },
  { key: "programador.skills.web.description", page: "programador", label: "Habilidade Web: descrição", defaultPt: "Integração de sistemas via REST, GraphQL e WebSockets." },
  { key: "programador.skills.ai.title", page: "programador", label: "Habilidade IA: título", defaultPt: "Inteligência Artificial" },
  { key: "programador.skills.ai.description", page: "programador", label: "Habilidade IA: descrição", defaultPt: "Uso, adaptação e desenvolvimento de modelos de acordo com a necessidade da aplicação." },

  // Empreendedor
  { key: "empreendedor.title", page: "empreendedor", label: "Título da página", defaultPt: "Empreendedor" },
  { key: "empreendedor.story.p1", page: "empreendedor", label: "História: parágrafo 1", multiline: true, defaultPt: "Minha trajetória empreendedora nasceu do mesmo propósito que me levou à tecnologia: a vontade de criar, experimentar e transformar ideias em soluções reais. Antes mesmo da programação, eu já explorava diferentes formas de construir e resolver problemas, através de atividades como marcenaria e eletrônica." },
  { key: "empreendedor.story.p2", page: "empreendedor", label: "História: parágrafo 2", multiline: true, defaultPt: "Quando comecei a programar, encontrei uma nova forma de criar: em vez de construir apenas objetos físicos, passei a desenvolver sistemas capazes de automatizar processos, organizar informações e resolver necessidades de pessoas e negócios." },
  { key: "empreendedor.story.p3", page: "empreendedor", label: "História: parágrafo 3", multiline: true, defaultPt: "Ao longo da minha jornada, tive contato com diferentes áreas e profissionais, desenvolvendo uma visão ampla sobre como problemas reais surgem e como soluções digitais podem gerar valor. Essa experiência me levou a transformar a TYTO, a comunidade de estudos que eu havia fundado com outros universitários de computação, na minha própria empresa, em julho de 2021." },
  { key: "empreendedor.story.p4", page: "empreendedor", label: "História: parágrafo 4", multiline: true, defaultPt: "A oportunidade surgiu a partir de uma demanda real de um cliente que precisava de um web app. O projeto marcou minha transição de desenvolvedor e designer para alguém responsável por entender problemas de negócio, definir soluções, construir produtos e entregar resultados." },
  { key: "empreendedor.story.p5", page: "empreendedor", label: "História: parágrafo 5", multiline: true, defaultPt: "Durante essa fase, explorei diferentes mercados em busca de problemas relevantes que pudessem ser resolvidos através de software, incluindo setores como condomínios, hotelaria e investimentos. Esse processo me ensinou uma das principais lições da engenharia de software aplicada a negócios: a tecnologia só tem valor quando resolve problemas reais." },
  { key: "empreendedor.story.p6", page: "empreendedor", label: "História: parágrafo 6", multiline: true, defaultPt: "Essa busca me levou posteriormente a uma oportunidade inesperada no setor de engenharia diagnóstica, onde comecei a desenvolver uma solução envolvendo análise estrutural, modelos matemáticos e inteligência artificial." },
  { key: "empreendedor.principles.heading", page: "empreendedor", label: "Lições: título", defaultPt: "O Que Aprendi Empreendendo" },
  { key: "empreendedor.principles.money.title", page: "empreendedor", label: "Lição 1: título", defaultPt: "Tecnologia como alavanca" },
  { key: "empreendedor.principles.money.description", page: "empreendedor", label: "Lição 1: descrição", multiline: true, defaultPt: "Vi isso de perto na engenharia diagnóstica: uma vistoria que levava meses virou questão de horas com a EngScan. É esse tipo de alavancagem que busco em cada negócio: usar software pra fazer o mesmo trabalho valer muito mais." },
  { key: "empreendedor.principles.education.title", page: "empreendedor", label: "Lição 2: título", defaultPt: "Ensinar multiplica o negócio" },
  { key: "empreendedor.principles.education.description", page: "empreendedor", label: "Lição 2: descrição", multiline: true, defaultPt: "Toda empresa que fundei nasceu perto de gente que eu ajudei a formar: ligas acadêmicas, clubes de computação, centenas de alunos que ensinei a programar. Investir em quem vem depois sempre voltou como oportunidade." },
  { key: "empreendedor.principles.community.title", page: "empreendedor", label: "Lição 3: título", defaultPt: "Comunidade antes do produto" },
  { key: "empreendedor.principles.community.description", page: "empreendedor", label: "Lição 3: descrição", multiline: true, defaultPt: "A TYTO.club começou como comunidade de estudos, não como empresa. EngScan, Athena e os outros produtos nasceram de dentro dela. Prefiro construir a rede de pessoas primeiro; o produto certo aparece depois." },
  { key: "empreendedor.principles.startups.title", page: "empreendedor", label: "Lição 4: título", defaultPt: "O problema importa mais que o setor" },
  { key: "empreendedor.principles.startups.description", page: "empreendedor", label: "Lição 4: descrição", multiline: true, defaultPt: "Já levei software pra condomínios, hotelaria, investimentos, saúde, agronomia e engenharia civil. Não me prendo a um mercado: sigo o problema que vale a pena resolver, não o setor que está na moda." },
  { key: "empreendedor.vision.heading", page: "empreendedor", label: "Visão de mundo: título", defaultPt: "Visão de mundo" },
  { key: "empreendedor.vision.body", page: "empreendedor", label: "Visão de mundo: texto", defaultPt: "Sempre existe mais de um caminho para a solução de um problema." },

  // Universitário
  { key: "universitario.title", page: "universitario", label: "Título da página", defaultPt: "Universitário" },
  { key: "universitario.story.heading", page: "universitario", label: "Trajetória: título", defaultPt: "Universidade e construção de comunidades" },
  { key: "universitario.story.p1", page: "universitario", label: "Trajetória: parágrafo 1", multiline: true, defaultPt: "Ao ingressar na Universidade Federal de Sergipe em 2020, escolhi Ciência da Computação como uma forma de aprofundar uma paixão que já fazia parte da minha trajetória: transformar ideias em soluções através da tecnologia." },
  { key: "universitario.story.p2", page: "universitario", label: "Trajetória: parágrafo 2", multiline: true, defaultPt: "Durante a graduação, desenvolvi minha base em fundamentos de computação, lógica matemática e desenvolvimento de software, enquanto buscava aplicar esse conhecimento em projetos práticos. Além do aprendizado técnico, comecei a atuar na organização de grupos de estudo e projetos colaborativos, reunindo pessoas com interesses semelhantes para compartilhar conhecimento e construir soluções em conjunto." },
  { key: "universitario.story.p3", page: "universitario", label: "Trajetória: parágrafo 3", multiline: true, defaultPt: "Em 2021, junto com outros estudantes da área de computação, fundei a TYTO, inicialmente como uma comunidade de estudos voltada para troca de conhecimento, desenvolvimento técnico e colaboração entre alunos. O grupo cresceu a partir da ideia de que aprender tecnologia de forma colaborativa acelera a evolução de todos os envolvidos." },
  { key: "universitario.story.p4", page: "universitario", label: "Trajetória: parágrafo 4", multiline: true, defaultPt: "A partir dessas conexões, começamos a transformar ideias e experimentos em projetos mais estruturados. Algumas iniciativas nasceram inicialmente como pesquisas e protótipos acadêmicos e, posteriormente, evoluíram para produtos e startups, como a EngScan e o Ágora." },
  { key: "universitario.story.p5", page: "universitario", label: "Trajetória: parágrafo 5", multiline: true, defaultPt: "Essa experiência foi fundamental para minha formação como engenheiro: aprendi que construir software não envolve apenas tecnologia, mas também comunicação, liderança, colaboração e a capacidade de transformar conhecimento coletivo em soluções aplicáveis." },
  { key: "universitario.research.heading", page: "universitario", label: "Áreas de Pesquisa: título", defaultPt: "Áreas de Pesquisa" },
  { key: "universitario.research.civil.title", page: "universitario", label: "Pesquisa 1: título", defaultPt: "Redes Neurais aplicadas a Engenharia Civil Diagnóstica" },
  { key: "universitario.research.civil.description", page: "universitario", label: "Pesquisa 1: descrição", defaultPt: "Machine Learning, Deep Learning, NLP" },
  { key: "universitario.research.blockchain.title", page: "universitario", label: "Pesquisa 2: título", defaultPt: "Blockchain" },
  { key: "universitario.research.blockchain.description", page: "universitario", label: "Pesquisa 2: descrição", defaultPt: "Análise de dados, visualização, estatística" },
  { key: "universitario.research.animal.title", page: "universitario", label: "Pesquisa 3: título", defaultPt: "Mapeamento animal na agropecuária" },
  { key: "universitario.research.animal.description", page: "universitario", label: "Pesquisa 3: descrição", defaultPt: "Arquitetura, padrões, metodologias" },
  { key: "universitario.research.applied.title", page: "universitario", label: "Pesquisa 4: título", defaultPt: "Pesquisa Aplicada" },
  { key: "universitario.research.applied.description", page: "universitario", label: "Pesquisa 4: descrição", defaultPt: "Soluções práticas para problemas reais" },
  { key: "universitario.contributions.heading", page: "universitario", label: "Contribuições Acadêmicas: título", defaultPt: "Contribuições Acadêmicas" },
  { key: "universitario.contributions.p1", page: "universitario", label: "Contribuições: parágrafo 1", multiline: true, defaultPt: "Fundador do clube de tecnologia e computação (TYTO.club) e também cofundador da Liga Acadêmica de Desenvolvimento Web da UFS, tenho atuado na interseção entre ensino, pesquisa e aplicação prática. Ao longo dos anos, ensinei muitos estudantes de diferentes cursos a programar, criando pontes entre teoria e prática." },
  { key: "universitario.contributions.p2", page: "universitario", label: "Contribuições: parágrafo 2", multiline: true, defaultPt: "Iniciei pesquisas acadêmicas autônomas e, dentro do TYTO.club, estruturei um laboratório de pesquisa e um fluxo claro de transformação: da investigação, prototipagem e implementação social. Esse processo permitiu estender o clube para outros estados e garantir que os resultados acadêmicos gerem impacto real na comunidade, seja por ferramentas, parcerias ou projetos aplicados." },

  // Labels shared across every project detail page (atenas + portfolio/*), only truly
  // identical wording goes here; anything that varies per page (e.g. "Função" vs "Atuação")
  // stays namespaced under that page's own keys instead.
  { key: "projectDetail.back", page: "projectDetail", label: "Botão: voltar para o Portfolio", defaultPt: "Voltar para o Portfolio" },
  { key: "projectDetail.techSheet", page: "projectDetail", label: "Título: ficha técnica", defaultPt: "Ficha Técnica" },
  { key: "projectDetail.period", page: "projectDetail", label: "Rótulo: período", defaultPt: "Período" },
  { key: "projectDetail.status", page: "projectDetail", label: "Rótulo: status", defaultPt: "Status" },

  // Atenas (Athena)
  { key: "atenas.title", page: "atenas", label: "Título", defaultPt: "Deusa Athena" },
  { key: "atenas.subtitle", page: "atenas", label: "Subtítulo", defaultPt: "A inteligência por trás do TYTO.club: gamificação, automação e mentoria por IA" },
  { key: "atenas.date", page: "atenas", label: "Período", defaultPt: "2023 - Presente" },
  { key: "atenas.role", page: "atenas", label: "Função (ficha técnica)", defaultPt: "Criador & Lead AI/Backend Developer" },
  { key: "atenas.labels.role", page: "atenas", label: "Rótulo: função", defaultPt: "Função" },
  { key: "atenas.labels.techStack", page: "atenas", label: "Título: tecnologias envolvidas", defaultPt: "Tecnologias Envolvidas" },
  { key: "atenas.status", page: "atenas", label: "Status (ficha técnica)", defaultPt: "Ativa e em Evolução" },
  { key: "atenas.overview.heading", page: "atenas", label: "Visão Geral: título", defaultPt: "Visão Geral da Athena" },
  { key: "atenas.overview.body", page: "atenas", label: "Visão Geral: texto", multiline: true, defaultPt: "Athena é a assistente inteligente central do TYTO.club. Ela centraliza e gerencia a gamificação (XP e tokens), automatiza a gestão de tarefas e cargos em plataformas como Discord e WhatsApp, agenda reuniões, propõe desafios práticos de desenvolvimento e, de forma inovadora, avalia soluções de código submetidas pelos membros. Com o 'Oráculo', Athena oferece respostas instantâneas, garantindo uma experiência interativa e gamificada para todos os clubistas." },
  { key: "atenas.challenges.heading", page: "atenas", label: "Desafios: título", defaultPt: "Os Desafios da Construção" },
  { key: "atenas.challenges.item1", page: "atenas", label: "Desafio 1", defaultPt: "Integrar múltiplas plataformas (Discord, WhatsApp) e APIs de IA de forma coesa." },
  { key: "atenas.challenges.item2", page: "atenas", label: "Desafio 2", defaultPt: "Desenvolver um sistema robusto de gamificação com XP e tokens em tempo real." },
  { key: "atenas.challenges.item3", page: "atenas", label: "Desafio 3", defaultPt: "Criar um avaliador de código baseado em IA que forneça feedback útil e preciso." },
  { key: "atenas.challenges.item4", page: "atenas", label: "Desafio 4", defaultPt: "Gerenciar a persistência de dados complexos (gamificação, tarefas, históricos) de forma escalável." },
  { key: "atenas.solutions.heading", page: "atenas", label: "Soluções: título", defaultPt: "As Soluções Implementadas" },
  { key: "atenas.solutions.item1", page: "atenas", label: "Solução 1", defaultPt: "Arquitetura modular baseada em micro-serviços (ou módulos bem definidos) para cada integração." },
  { key: "atenas.solutions.item2", page: "atenas", label: "Solução 2", defaultPt: "Backend em Node.js com TypeScript para gerenciar a lógica de gamificação e as interações." },
  { key: "atenas.solutions.item3", page: "atenas", label: "Solução 3", defaultPt: "Uso da OpenAI API para processamento de linguagem natural e avaliação inteligente de código." },
  { key: "atenas.solutions.item4", page: "atenas", label: "Solução 4", defaultPt: "Implementação de um banco de dados PostgreSQL para dados relacionais e Redis para cache de alta performance." },
  { key: "atenas.solutions.item5", page: "atenas", label: "Solução 5", defaultPt: "Sistema de fila (RabbitMQ) para processar requisições assíncronas de IA e interações de chat sem gargalos." },
  { key: "atenas.features.heading", page: "atenas", label: "Recursos: título", defaultPt: "Recursos e Funcionalidades Chave" },
  { key: "atenas.features.intro", page: "atenas", label: "Recursos: introdução", defaultPt: "Athena não é apenas um bot, mas um ecossistema inteligente que impulsiona o engajamento e o aprendizado no TYTO.club." },
  { key: "atenas.features.gamification.title", page: "atenas", label: "Recurso 1: título", defaultPt: "Gamificação Centralizada" },
  { key: "atenas.features.gamification.description", page: "atenas", label: "Recurso 1: descrição", defaultPt: "Gerencia XP, tokens e recompensas para manter os clubistas engajados." },
  { key: "atenas.features.automation.title", page: "atenas", label: "Recurso 2: título", defaultPt: "Automação Inteligente" },
  { key: "atenas.features.automation.description", page: "atenas", label: "Recurso 2: descrição", defaultPt: "Administra tarefas, cargos e a organização em Discord e WhatsApp." },
  { key: "atenas.features.mentoring.title", page: "atenas", label: "Recurso 3: título", defaultPt: "Mentoria por IA e Avaliação de Código" },
  { key: "atenas.features.mentoring.description", page: "atenas", label: "Recurso 3: descrição", defaultPt: "Propõe desafios de código e avalia as soluções, oferecendo feedback construtivo." },
  { key: "atenas.features.oracle.title", page: "atenas", label: "Recurso 4: título", defaultPt: "Oráculo de Respostas Instantâneas" },
  { key: "atenas.features.oracle.description", page: "atenas", label: "Recurso 4: descrição", defaultPt: "Disponibiliza um canal para respostas rápidas e dúvidas dos clubistas." },
  { key: "atenas.flow.placeholder", page: "atenas", label: "Placeholder do fluxo de interação", defaultPt: "[Fluxo de Interação da Athena: Usuário → Discord/WhatsApp → Athena Bot (Node.js) → OpenAI API / PostgreSQL]" },
  { key: "atenas.links.demo", page: "atenas", label: "Botão: visitar TYTO.club", defaultPt: "Visitar TYTO.club" },
  { key: "atenas.links.github", page: "atenas", label: "Botão: ver repositório", defaultPt: "TYTO.club no GitHub" },

  // Portfolio: TYTO.club
  { key: "tyto.title", page: "portfolio/tyto", label: "Título", defaultPt: "TYTO.club" },
  { key: "tyto.subtitle", page: "portfolio/tyto", label: "Subtítulo", multiline: true, defaultPt: "Comunidade internacional de tecnologia que fundei em 2021, hoje uma plataforma com economia gamificada, governança simulada e projetos reais para squads" },
  { key: "tyto.date", page: "portfolio/tyto", label: "Período", defaultPt: "2021 - Presente" },
  { key: "tyto.role", page: "portfolio/tyto", label: "Função (ficha técnica)", defaultPt: "Fundador & Lead Engineer" },
  { key: "tyto.status", page: "portfolio/tyto", label: "Status (ficha técnica)", defaultPt: "Em Produção" },
  { key: "tyto.architectureValue", page: "portfolio/tyto", label: "Arquitetura (ficha técnica)", defaultPt: "SPA + REST dedicado" },
  { key: "tyto.labels.role", page: "portfolio/tyto", label: "Rótulo: função", defaultPt: "Atuação" },
  { key: "tyto.labels.techStack", page: "portfolio/tyto", label: "Título: stack tecnológica", defaultPt: "Stack Tecnológica" },
  { key: "tyto.labels.architecture", page: "portfolio/tyto", label: "Rótulo: arquitetura", defaultPt: "Arquitetura" },
  { key: "tyto.overview.heading", page: "portfolio/tyto", label: "Visão Geral: título", defaultPt: "Visão Geral" },
  {
    key: "tyto.overview.body",
    page: "portfolio/tyto",
    label: "Visão Geral: texto",
    multiline: true,
    defaultPt: "Fundei o TYTO.club em 2021, inicialmente como uma comunidade de estudos entre universitários de computação, e conduzi seu crescimento até a plataforma atual: um ecossistema onde membros acumulam XP, sobem de patente, ganham Dracmas (moeda interna) cumprindo missões, lideram ou participam de projetos reais e operam uma camada de governança simulada com Reinos, Polis, eleições e um tribunal monetário. Arquitetei e desenvolvi a plataforma do zero: frontend em React 19 + TypeScript + Vite, Firebase (Auth + Firestore) como base de dados primária para leituras em tempo real, e um backend REST dedicado para as regras de negócio mais sensíveis, como economia e missões.",
  },
  { key: "tyto.features.heading", page: "portfolio/tyto", label: "Recursos: título", defaultPt: "O que a plataforma faz" },
  { key: "tyto.features.progression.title", page: "portfolio/tyto", label: "Recurso 1: título", defaultPt: "Progressão" },
  { key: "tyto.features.progression.description", page: "portfolio/tyto", label: "Recurso 1: descrição", multiline: true, defaultPt: "XP e 14 patentes (de Neófito a Dominador), cada uma com perks reais de acesso a projetos e benefícios. Conquistas concedidas por transação atômica." },
  { key: "tyto.features.economy.title", page: "portfolio/tyto", label: "Recurso 2: título", defaultPt: "Economia (Dracmas)" },
  { key: "tyto.features.economy.description", page: "portfolio/tyto", label: "Recurso 2: descrição", multiline: true, defaultPt: "Moeda interna com histórico completo de transações, taxa mensal automática, empréstimos e reserva lastreada em dinheiro real." },
  { key: "tyto.features.governance.title", page: "portfolio/tyto", label: "Recurso 3: título", defaultPt: "Governança" },
  { key: "tyto.features.governance.description", page: "portfolio/tyto", label: "Recurso 3: descrição", multiline: true, defaultPt: "Reinos e Polis com cargos eletivos (Tribuno, Conselheiro, Dux Vecturium, Guarda Pretoriana), mandatos com prazo e impeachment por voto." },
  { key: "tyto.features.projects.title", page: "portfolio/tyto", label: "Recurso 4: título", defaultPt: "Projetos & Squads" },
  { key: "tyto.features.projects.description", page: "portfolio/tyto", label: "Recurso 4: descrição", multiline: true, defaultPt: "Papéis de líder/parceiro/colaborador por projeto, métricas reais de negócio (MRR, burn rate, churn) resumidas em um índice único de progresso." },
  { key: "tyto.challenges.heading", page: "portfolio/tyto", label: "Desafio: título", defaultPt: "O Desafio" },
  { key: "tyto.challenges.item1", page: "portfolio/tyto", label: "Desafio 1", multiline: true, defaultPt: "Conceder conquistas sem duplicar ou perder registros quando duas rotinas do app disparavam a mesma verificação quase ao mesmo tempo, para membros diferentes competindo pelas mesmas metas." },
  { key: "tyto.challenges.item2", page: "portfolio/tyto", label: "Desafio 2", multiline: true, defaultPt: "Proteger campos financeiros e de hierarquia (saldo, patente, cargos eletivos) sem depender só da interface: em um sistema onde XP e Dracmas valem \"moeda real\" dentro da comunidade, qualquer brecha de escrita direta vira uma forma de trapaça." },
  { key: "tyto.challenges.item3", page: "portfolio/tyto", label: "Desafio 3", multiline: true, defaultPt: "Modelar em código uma estrutura de governança inteira (Reino, Polis, Colônias/Metrópoles, cargos eletivos com mandato e impeachment, tribunal monetário), mantendo tudo fiel a regulamentos escritos em prosa que evoluem junto com a comunidade." },
  { key: "tyto.solutions.heading", page: "portfolio/tyto", label: "Solução: título", defaultPt: "A Solução" },
  { key: "tyto.solutions.item1", page: "portfolio/tyto", label: "Solução 1", multiline: true, defaultPt: "Concessão de conquistas dentro de uma transação atômica do Firestore em vez de escritas simples: a transação sempre lê o estado já confirmado (não o que está em memória) e, de quebra, repara sozinha registros duplicados deixados por corridas passadas." },
  { key: "tyto.solutions.item2", page: "portfolio/tyto", label: "Solução 2", multiline: true, defaultPt: "Regras do Firestore com mais de 950 linhas como autoridade real de acesso, não só a UI: funções dedicadas bloqueiam qualquer escrita direta do usuário a saldo, patente ou cargo, e a suspensão automática por saldo negativo é reforçada tanto no client quanto no servidor." },
  { key: "tyto.solutions.item3", page: "portfolio/tyto", label: "Solução 3", multiline: true, defaultPt: "Os regulamentos internos (a \"Carta Institucional\", em Markdown) são a fonte da verdade do domínio, e o código é a implementação deles: cargos eletivos, mandatos e o tribunal monetário viram tipos e serviços dedicados, revisáveis independentemente do texto institucional." },
  { key: "tyto.architecture.heading", page: "portfolio/tyto", label: "Arquitetura: título", defaultPt: "Arquitetura do Sistema" },
  { key: "tyto.architecture.body", page: "portfolio/tyto", label: "Arquitetura: texto", multiline: true, defaultPt: "O frontend fala com dois backends distintos por design: a maior parte das leituras (e algumas escritas) vai direto do navegador para o Firestore em tempo real, enquanto a economia, projetos e missões (a lógica de negócio mais sensível) passam por um backend REST dedicado, autenticado com o token do Firebase." },
  { key: "tyto.architecture.diagram.frontend", page: "portfolio/tyto", label: "Diagrama: linha frontend", defaultPt: "React 19 + Vite + TypeScript: Firebase Auth, estado do usuário assinado em tempo real (onSnapshot)" },
  { key: "tyto.architecture.diagram.arrow1", page: "portfolio/tyto", label: "Diagrama: seta 1", defaultPt: "↓ dois caminhos de dados" },
  { key: "tyto.architecture.diagram.firestoreTag", page: "portfolio/tyto", label: "Diagrama: rótulo Firestore", defaultPt: "[Firestore direto]" },
  { key: "tyto.architecture.diagram.firestore", page: "portfolio/tyto", label: "Diagrama: linha Firestore", defaultPt: "Leituras e escritas simples via SDK client, tempo real" },
  { key: "tyto.architecture.diagram.backend", page: "portfolio/tyto", label: "Diagrama: linha backend", defaultPt: "Economia, projetos, missões: fetch + Bearer <ID token>" },
  { key: "tyto.architecture.diagram.arrow2", page: "portfolio/tyto", label: "Diagrama: seta 2", defaultPt: "↓ controle de acesso" },
  { key: "tyto.architecture.diagram.rules", page: "portfolio/tyto", label: "Diagrama: linha regras", defaultPt: "950+ linhas: autoridade real de acesso, não a interface" },
  { key: "tyto.security.heading", page: "portfolio/tyto", label: "Segurança: título", defaultPt: "Segurança como Camada Real, não de Conveniência" },
  { key: "tyto.security.intro", page: "portfolio/tyto", label: "Segurança: introdução", multiline: true, defaultPt: "Mais de 45 coleções têm regras dedicadas no Firestore, cada uma derivando leitura/escrita de uma combinação de autenticação, membership de Polis/Reino/projeto, cargo eletivo ativo ou admin global:" },
  { key: "tyto.security.item1", page: "portfolio/tyto", label: "Segurança: item 1", multiline: true, defaultPt: "Campos sensíveis (saldo, patente, cargos) nunca são editáveis pelo próprio usuário via escrita direta, apenas por transações server-side/admin." },
  { key: "tyto.security.item2", page: "portfolio/tyto", label: "Segurança: item 2", multiline: true, defaultPt: "Permissão de projetos é derivada diretamente do papel do membro (líder, parceiro, colaborador), validada nas regras, não apenas escondida na UI." },
  { key: "tyto.links.demo", page: "portfolio/tyto", label: "Botão: acessar plataforma", defaultPt: "Acessar Plataforma" },
  { key: "tyto.links.github", page: "portfolio/tyto", label: "Botão: repositório da organização", defaultPt: "Repositório da Organização" },

  // Portfolio: Maestro
  { key: "maestro.title", page: "portfolio/maestro", label: "Título", defaultPt: "Maestro" },
  { key: "maestro.subtitle", page: "portfolio/maestro", label: "Subtítulo", multiline: true, defaultPt: "Orquestrador local de agentes de IA para desenvolvimento: CLI e API que planejam, implementam e testam código em worktrees Git isolados" },
  { key: "maestro.date", page: "portfolio/maestro", label: "Período", defaultPt: "2026" },
  { key: "maestro.role", page: "portfolio/maestro", label: "Função (ficha técnica)", defaultPt: "Criador & Arquiteto Solo" },
  { key: "maestro.status", page: "portfolio/maestro", label: "Status (ficha técnica)", defaultPt: "Em desenvolvimento ativo" },
  { key: "maestro.agentsValue", page: "portfolio/maestro", label: "Agentes (ficha técnica)", defaultPt: "26 especializados" },
  { key: "maestro.testsValue", page: "portfolio/maestro", label: "Testes (ficha técnica)", defaultPt: "108 automatizados" },
  { key: "maestro.labels.role", page: "portfolio/maestro", label: "Rótulo: função", defaultPt: "Atuação" },
  { key: "maestro.labels.techStack", page: "portfolio/maestro", label: "Título: stack tecnológica", defaultPt: "Stack Tecnológica" },
  { key: "maestro.labels.agents", page: "portfolio/maestro", label: "Rótulo: agentes", defaultPt: "Agentes" },
  { key: "maestro.labels.tests", page: "portfolio/maestro", label: "Rótulo: testes", defaultPt: "Testes" },
  { key: "maestro.terminal.task", page: "portfolio/maestro", label: "Terminal: objetivo da tarefa", defaultPt: "Adicionar validação de CPF" },
  { key: "maestro.terminal.planCreated", page: "portfolio/maestro", label: "Terminal: plano criado", defaultPt: "plano criado, repositório limpo, aguardando confirmação" },
  { key: "maestro.terminal.planId", page: "portfolio/maestro", label: "Terminal: id do plano", defaultPt: "id-do-plano" },
  { key: "maestro.terminal.branchCreated", page: "portfolio/maestro", label: "Terminal: branch criada", defaultPt: "branch maestro/<id> criada em worktree isolado" },
  { key: "maestro.terminal.pipeline", page: "portfolio/maestro", label: "Terminal: pipeline", defaultPt: "pipeline: contexto → requisitos → implementação → testes → revisão" },
  { key: "maestro.terminal.done", page: "portfolio/maestro", label: "Terminal: status concluído", defaultPt: "status: concluído" },
  { key: "maestro.overview.heading", page: "portfolio/maestro", label: "Visão Geral: título", defaultPt: "Visão Geral" },
  { key: "maestro.overview.body", page: "portfolio/maestro", label: "Visão Geral: texto", multiline: true, defaultPt: "Maestro é uma ferramenta local que coordena tarefas de desenvolvimento assistidas por IA em qualquer projeto que declare um maestro.yaml. A CLI (Typer) fala por HTTP com uma API FastAPI local, que aciona um Orchestrator responsável por selecionar contexto, montar um plano, exigir confirmação explícita e só então executar a escrita em uma branch e worktree Git isolados. A integração de produção com o modelo é feita exclusivamente pela CLI Codex já instalada na máquina; os testes usam fakes e nunca chamam um provider real." },
  { key: "maestro.features.heading", page: "portfolio/maestro", label: "Recursos: título", defaultPt: "O que a ferramenta faz" },
  { key: "maestro.features.pipeline.title", page: "portfolio/maestro", label: "Recurso 1: título", defaultPt: "Pipeline em fases" },
  { key: "maestro.features.pipeline.description", page: "portfolio/maestro", label: "Recurso 1: descrição", multiline: true, defaultPt: "Máquina de estados fixa (contexto → plano → decisão arquitetural → execução → testes/revisão). Fases futuras como DOCUMENTING e ROLLED_BACK já estão declaradas para expansão." },
  { key: "maestro.features.agents.title", page: "portfolio/maestro", label: "Recurso 2: título", defaultPt: "26 agentes especializados" },
  { key: "maestro.features.agents.description", page: "portfolio/maestro", label: "Recurso 2: descrição", multiline: true, defaultPt: "Do ContextAgent ao SecurityAgent, cada um resolve uma única etapa e devolve um SubAgentResult estruturado, nunca histórico de conversa bruto." },
  { key: "maestro.features.worktrees.title", page: "portfolio/maestro", label: "Recurso 3: título", defaultPt: "Escrita isolada em worktrees" },
  { key: "maestro.features.worktrees.description", page: "portfolio/maestro", label: "Recurso 3: descrição", multiline: true, defaultPt: "Toda tarefa que escreve roda numa branch e worktree Git próprios, exigindo repositório limpo e confirmação explícita antes de tocar no checkout principal." },
  { key: "maestro.features.cli.title", page: "portfolio/maestro", label: "Recurso 4: título", defaultPt: "CLI + API local" },
  { key: "maestro.features.cli.description", page: "portfolio/maestro", label: "Recurso 4: descrição", multiline: true, defaultPt: "Comandos Typer conversam por HTTP com uma API FastAPI restrita a 127.0.0.1:8765. Sem autenticação, sem rede externa, sem multiusuário, por design." },
  { key: "maestro.challenges.heading", page: "portfolio/maestro", label: "Desafio: título", defaultPt: "O Desafio" },
  { key: "maestro.challenges.item1", page: "portfolio/maestro", label: "Desafio 1", multiline: true, defaultPt: "Garantir que agentes com permissão de escrita nunca corrompam o checkout principal nem pisem no trabalho um do outro durante uma tarefa." },
  { key: "maestro.challenges.item2", page: "portfolio/maestro", label: "Desafio 2", multiline: true, defaultPt: "Impedir que um objetivo mal especificado dispare sozinho uma mudança estrutural (autenticação, migração de banco, contrato público) sem revisão humana." },
  { key: "maestro.challenges.item3", page: "portfolio/maestro", label: "Desafio 3", multiline: true, defaultPt: "Selecionar contexto suficiente para cada agente sem estourar o orçamento de tokens nem vazar instruções irrelevantes para o agente errado." },
  { key: "maestro.solutions.heading", page: "portfolio/maestro", label: "Solução: título", defaultPt: "A Solução" },
  { key: "maestro.solutions.item1", page: "portfolio/maestro", label: "Solução 1", multiline: true, defaultPt: "O Orchestrator serializa as fases de escrita com um lock de processo, e toda execução roda em uma branch maestro/<id> dentro de um worktree Git próprio, criado só depois de confirmar repositório limpo e consentimento explícito do usuário." },
  { key: "maestro.solutions.item2", page: "portfolio/maestro", label: "Solução 2", multiline: true, defaultPt: "Termos estruturais no objetivo forçam o formato DECISÃO ARQUITETURAL NECESSÁRIA: a execução fica bloqueada até uma decisão ser registrada, mesmo com --confirm passado." },
  { key: "maestro.solutions.item3", page: "portfolio/maestro", label: "Solução 3", multiline: true, defaultPt: "O ContextAgent monta um ContextPacket por tarefa: o AGENTS.md raiz sempre entra, um AGENTS.md aninhado só entra se um arquivo do seu diretório foi selecionado, e os contextos especializados em agent-context/ só carregam quando o objetivo ou os caminhos batem nas palavras-chave do link." },
  { key: "maestro.architecture.heading", page: "portfolio/maestro", label: "Arquitetura: título", defaultPt: "Arquitetura do Sistema" },
  { key: "maestro.architecture.body", page: "portfolio/maestro", label: "Arquitetura: texto", multiline: true, defaultPt: "A CLI nunca instancia agentes diretamente: ela é só um cliente HTTP da API local, que encaminha para o Orchestrator. Ele lê contexto e catálogo de agentes, delega ferramentas de filesystem, Git, terminal e testes, e conversa com o provider Codex por trás de um protocolo próprio, independente de modelo." },
  { key: "maestro.architecture.diagram.cli", page: "portfolio/maestro", label: "Diagrama: linha CLI", defaultPt: "Typer, cliente HTTP puro, sem importar agentes" },
  { key: "maestro.architecture.diagram.arrow1", page: "portfolio/maestro", label: "Diagrama: seta 1", defaultPt: "↓ HTTP local, 127.0.0.1:8765" },
  { key: "maestro.architecture.diagram.api", page: "portfolio/maestro", label: "Diagrama: linha API", defaultPt: "valida requisições e encaminha ao Orchestrator ou ao gerenciador de jobs" },
  { key: "maestro.architecture.diagram.arrow2", page: "portfolio/maestro", label: "Diagrama: seta 2", defaultPt: "↓ orquestra" },
  { key: "maestro.architecture.diagram.context", page: "portfolio/maestro", label: "Diagrama: linha ContextAgent", defaultPt: "seleciona AGENTS.md, código, testes e diff" },
  { key: "maestro.architecture.diagram.tools", page: "portfolio/maestro", label: "Diagrama: linha tools", defaultPt: "filesystem, Git, terminal, busca, testes" },
  { key: "maestro.architecture.diagram.provider", page: "portfolio/maestro", label: "Diagrama: linha provider", defaultPt: "execução real do modelo, atrás de um protocolo próprio" },
  { key: "maestro.security.heading", page: "portfolio/maestro", label: "Segurança: título", defaultPt: "Autonomia com Freio de Mão" },
  { key: "maestro.security.intro", page: "portfolio/maestro", label: "Segurança: introdução", multiline: true, defaultPt: "O objetivo do Maestro é dar autonomia real a agentes de IA sem abrir mão de controle sobre o que eles podem fazer sozinhos:" },
  { key: "maestro.security.item1", page: "portfolio/maestro", label: "Segurança: item 1", multiline: true, defaultPt: "Nenhuma escrita acontece sem repositório Git limpo e confirmação explícita; nenhum agente faz push ou altera configuração Git global." },
  { key: "maestro.security.item2", page: "portfolio/maestro", label: "Segurança: item 2", multiline: true, defaultPt: "Um redator dedicado evita gravar segredos, chaves ou conteúdo de .env em logs, contexto, planos ou respostas." },
  { key: "maestro.security.item3", page: "portfolio/maestro", label: "Segurança: item 3", multiline: true, defaultPt: "A API local não implementa autenticação nem isolamento multiusuário de propósito: ela nunca deve ser exposta além de 127.0.0.1, e o CORS aceita só dois dev servers locais." },
  { key: "maestro.links.github", page: "portfolio/maestro", label: "Botão: ver repositório", defaultPt: "Ver Repositório" },

  // Portfolio: Hefesto
  { key: "hefesto.title", page: "portfolio/hefesto", label: "Título", defaultPt: "Hefesto" },
  { key: "hefesto.subtitle", page: "portfolio/hefesto", label: "Subtítulo", multiline: true, defaultPt: "Assistente de IA pessoal e local-first que conhece de verdade os meus repositórios: cita arquivo, linha e commit em vez de inventar, e coordena agentes de escrita sob aprovação humana explícita" },
  { key: "hefesto.date", page: "portfolio/hefesto", label: "Período", defaultPt: "2026" },
  { key: "hefesto.role", page: "portfolio/hefesto", label: "Função (ficha técnica)", defaultPt: "Criador & Arquiteto Solo" },
  { key: "hefesto.status", page: "portfolio/hefesto", label: "Status (ficha técnica)", defaultPt: "Em desenvolvimento ativo" },
  { key: "hefesto.servicesValue", page: "portfolio/hefesto", label: "Serviços (ficha técnica)", defaultPt: "2 repositórios + orquestrador" },
  { key: "hefesto.testsValue", page: "portfolio/hefesto", label: "Testes (ficha técnica)", defaultPt: "244 backend + 152 frontend" },
  { key: "hefesto.labels.role", page: "portfolio/hefesto", label: "Rótulo: função", defaultPt: "Atuação" },
  { key: "hefesto.labels.techStack", page: "portfolio/hefesto", label: "Título: stack tecnológica", defaultPt: "Stack Tecnológica" },
  { key: "hefesto.labels.services", page: "portfolio/hefesto", label: "Rótulo: serviços", defaultPt: "Serviços" },
  { key: "hefesto.labels.tests", page: "portfolio/hefesto", label: "Rótulo: testes", defaultPt: "Testes" },
  { key: "hefesto.chatDemo.question", page: "portfolio/hefesto", label: "Demo de chat: pergunta", defaultPt: "Como o front reconecta o stream sem perder eventos?" },
  { key: "hefesto.chatDemo.answer", page: "portfolio/hefesto", label: "Demo de chat: resposta", multiline: true, defaultPt: "O endpoint mantém um log append-only por execução. Ao reconectar, o navegador envia o Last-Event-ID e a API reproduz só os eventos que faltaram, sem duplicar nada." },
  { key: "hefesto.overview.heading", page: "portfolio/hefesto", label: "Visão Geral: título", defaultPt: "Visão Geral" },
  { key: "hefesto.overview.body", page: "portfolio/hefesto", label: "Visão Geral: texto", multiline: true, defaultPt: "Hefesto nasceu de dois problemas do meu dia a dia como desenvolvedor: assistentes de IA genéricas alucinam sobre um repositório quando o contexto é só um recorte ad hoc, e ferramentas que 'escrevem código sozinhas' costumam esconder o quanto de autonomia real estão exercendo. Em vez de um chatbot plugado num repositório, é uma assistente com memória estruturada do histórico do projeto (commits → documentos → decisões → perguntas em aberto → conversas) e uma camada separada de execução autônoma, com aprovação humana obrigatória e isolamento real de escrita." },
  { key: "hefesto.features.heading", page: "portfolio/hefesto", label: "Recursos: título", defaultPt: "O que a assistente faz" },
  { key: "hefesto.features.sourced.title", page: "portfolio/hefesto", label: "Recurso 1: título", defaultPt: "Respostas com fonte, sempre" },
  { key: "hefesto.features.sourced.description", page: "portfolio/hefesto", label: "Recurso 1: descrição", multiline: true, defaultPt: "Toda resposta sobre documentação ou código cita path, linha inicial/final e hash do commit de onde a informação saiu. Sem evidência no repositório, a resposta diz isso em vez de inventar." },
  { key: "hefesto.features.voice.title", page: "portfolio/hefesto", label: "Recurso 2: título", defaultPt: "Conversa por voz ponta a ponta" },
  { key: "hefesto.features.voice.description", page: "portfolio/hefesto", label: "Recurso 2: descrição", multiline: true, defaultPt: "Grava, transcreve localmente com Whisper (CPU), responde e narra de volta usando a Web Speech API nativa do navegador, sem pipeline de áudio extra nem chave de API obrigatória." },
  { key: "hefesto.features.streaming.title", page: "portfolio/hefesto", label: "Recurso 3: título", defaultPt: "Streaming resiliente a reconexão" },
  { key: "hefesto.features.streaming.description", page: "portfolio/hefesto", label: "Recurso 3: descrição", multiline: true, defaultPt: "O chat em stream mantém um log append-only por execução; reconectar reproduz só os eventos que faltaram via Last-Event-ID, sem duplicar nem perder nada." },
  { key: "hefesto.features.isolated.title", page: "portfolio/hefesto", label: "Recurso 4: título", defaultPt: "Escrita isolada e aprovada" },
  { key: "hefesto.features.isolated.description", page: "portfolio/hefesto", label: "Recurso 4: descrição", multiline: true, defaultPt: "A tela de agentes leva ao orquestrador de escrita: cada tarefa roda numa branch e worktree isolados, com aprovação humana explícita antes de qualquer mudança em disco." },
  { key: "hefesto.challenges.heading", page: "portfolio/hefesto", label: "Desafio: título", defaultPt: "O Desafio" },
  { key: "hefesto.challenges.item1", page: "portfolio/hefesto", label: "Desafio 1", multiline: true, defaultPt: "Garantir que o chat em stream sobreviva a uma reconexão do navegador sem duplicar nem perder nenhum evento, mesmo com o EventSource tentando reconectar sozinho depois de uma resposta já ter terminado." },
  { key: "hefesto.challenges.item2", page: "portfolio/hefesto", label: "Desafio 2", multiline: true, defaultPt: "Fazer com que toda resposta cite arquivo, linha e commit reais, não uma aproximação: inventar uma citação seria pior do que admitir que não encontrou evidência." },
  { key: "hefesto.challenges.item3", page: "portfolio/hefesto", label: "Desafio 3", multiline: true, defaultPt: "Coordenar múltiplos agentes de IA sobre o mesmo repositório expôs um comportamento não determinístico: às vezes um provider respondia como se não tivesse acesso a um arquivo que estava, de fato, disponível no sandbox." },
  { key: "hefesto.solutions.heading", page: "portfolio/hefesto", label: "Solução: título", defaultPt: "A Solução" },
  { key: "hefesto.solutions.item1", page: "portfolio/hefesto", label: "Solução 1", multiline: true, defaultPt: "Cada execução mantém um log append-only de eventos por trás do endpoint de stream; a reconexão usa o Last-Event-ID do navegador para retomar exatamente do ponto onde parou, em vez de reiniciar a resposta." },
  { key: "hefesto.solutions.item2", page: "portfolio/hefesto", label: "Solução 2", multiline: true, defaultPt: "Escopo padrão é sempre 'só documentação'; código só entra com --scope code explícito, e cada resposta carrega path, linhas e hash do commit de onde a informação saiu, ou diz que não sabe." },
  { key: "hefesto.solutions.item3", page: "portfolio/hefesto", label: "Solução 3", multiline: true, defaultPt: "A lição virou prática de engenharia: tratar toda resposta de agente como potencialmente inconsistente, nunca como uma chamada de função garantida, e isolar qualquer escrita em branch e worktree próprios, revisáveis antes de qualquer merge." },
  { key: "hefesto.architecture.heading", page: "portfolio/hefesto", label: "Arquitetura: título", defaultPt: "Arquitetura do Sistema" },
  { key: "hefesto.architecture.body", page: "portfolio/hefesto", label: "Arquitetura: texto", multiline: true, defaultPt: "Três serviços locais independentes, cada um seu próprio repositório, conversando por HTTP em loopback e nunca expostos fora da máquina. O front web é a porta de entrada visual tanto do chat de documentação quanto do orquestrador de agentes de escrita." },
  { key: "hefesto.architecture.diagram.front", page: "portfolio/hefesto", label: "Diagrama: linha front", multiline: true, defaultPt: "React 19 + TanStack Router/Query, localhost:5174, chat, timeline de commits, leitura em voz alta, tela de agentes" },
  { key: "hefesto.architecture.diagram.frontTag", page: "portfolio/hefesto", label: "Diagrama: rótulo front", defaultPt: "[Front web]" },
  { key: "hefesto.architecture.diagram.chatTag", page: "portfolio/hefesto", label: "Diagrama: rótulo backend de chat", defaultPt: "[Backend de chat]" },
  { key: "hefesto.architecture.diagram.orchestratorTag", page: "portfolio/hefesto", label: "Diagrama: rótulo orquestrador", defaultPt: "[Orquestrador de agentes]" },
  { key: "hefesto.architecture.diagram.arrow", page: "portfolio/hefesto", label: "Diagrama: seta", defaultPt: "↓ HTTP local, contrato OpenAPI tipado" },
  { key: "hefesto.architecture.diagram.chat", page: "portfolio/hefesto", label: "Diagrama: linha backend de chat", multiline: true, defaultPt: "FastAPI, 127.0.0.1:8000, indexa commits/docs em SQLite, cita path + linha + commit em toda resposta" },
  { key: "hefesto.architecture.diagram.orchestrator", page: "portfolio/hefesto", label: "Diagrama: linha orquestrador", multiline: true, defaultPt: "FastAPI, 127.0.0.1:8765, escrita isolada em branch/worktree, sob aprovação humana" },
  { key: "hefesto.architecture.maestroNote", page: "portfolio/hefesto", label: "Nota sobre o Maestro", defaultPt: "O orquestrador de agentes é um projeto próprio, com página dedicada:" },
  { key: "hefesto.architecture.maestroLink", page: "portfolio/hefesto", label: "Link: veja o Maestro", defaultPt: "veja o Maestro" },
  { key: "hefesto.security.heading", page: "portfolio/hefesto", label: "Segurança: título", defaultPt: "Local-First por Padrão Real" },
  { key: "hefesto.security.intro", page: "portfolio/hefesto", label: "Segurança: introdução", defaultPt: "Local-first aqui não é discurso de marketing, é a premissa de projeto:" },
  { key: "hefesto.security.item1", page: "portfolio/hefesto", label: "Segurança: item 1", multiline: true, defaultPt: "As três APIs escutam só em 127.0.0.1, sem autenticação, porque nunca deveriam sair da máquina; CORS restrito às origens locais conhecidas dos próprios dev servers." },
  { key: "hefesto.security.item2", page: "portfolio/hefesto", label: "Segurança: item 2", multiline: true, defaultPt: "Nada é escrito sem aprovação explícita, seja uma edição pontual de arquivo no chat ou uma tarefa completa de agentes, e a escrita é sempre isolada em branch e worktree próprios." },
  { key: "hefesto.security.item3", page: "portfolio/hefesto", label: "Segurança: item 3", multiline: true, defaultPt: "Redação de segredos em múltiplas camadas: variáveis de ambiente nunca entram na configuração persistida, e padrões de chave/token/senha são removidos de contexto, diffs, logs e respostas antes de serem gravados." },
  { key: "hefesto.security.item4Prefix", page: "portfolio/hefesto", label: "Segurança: item 4 (antes dos comandos)", defaultPt: "Comandos destrutivos de Git/terminal" },
  { key: "hefesto.security.item4Suffix", page: "portfolio/hefesto", label: "Segurança: item 4 (depois dos comandos)", defaultPt: "e equivalentes) são bloqueados por política, a menos que explicitamente confirmados." },
  { key: "hefesto.links.backend", page: "portfolio/hefesto", label: "Botão: backend no GitHub", defaultPt: "Backend no GitHub" },
  { key: "hefesto.links.frontend", page: "portfolio/hefesto", label: "Botão: frontend no GitHub", defaultPt: "Frontend no GitHub" },

  // Portfolio: Monitor de Plantas
  { key: "plantas.title", page: "portfolio/plantas", label: "Título", defaultPt: "Monitor de Plantas" },
  { key: "plantas.subtitle", page: "portfolio/plantas", label: "Subtítulo", multiline: true, defaultPt: "Sistema doméstico de rega automática: sensores e câmera avaliam as plantas em tempo real, um ESP32 rega sozinho quando necessário, e um dashboard PWA mostra tudo sem depender de nuvem" },
  { key: "plantas.date", page: "portfolio/plantas", label: "Período", defaultPt: "2026" },
  { key: "plantas.role", page: "portfolio/plantas", label: "Função (ficha técnica)", defaultPt: "Criador & Arquiteto Solo (hardware, firmware e backend)" },
  { key: "plantas.status", page: "portfolio/plantas", label: "Status (ficha técnica)", defaultPt: "Funcional, rodando em casa" },
  { key: "plantas.partsValue", page: "portfolio/plantas", label: "Peças do sistema (ficha técnica)", defaultPt: "2 firmwares + backend + PWA" },
  { key: "plantas.databaseValue", page: "portfolio/plantas", label: "Banco de dados (ficha técnica)", defaultPt: "SQLite local (WAL)" },
  { key: "plantas.labels.role", page: "portfolio/plantas", label: "Rótulo: função", defaultPt: "Atuação" },
  { key: "plantas.labels.techStack", page: "portfolio/plantas", label: "Título: stack tecnológica", defaultPt: "Stack Tecnológica" },
  { key: "plantas.labels.parts", page: "portfolio/plantas", label: "Rótulo: peças do sistema", defaultPt: "Peças do sistema" },
  { key: "plantas.labels.database", page: "portfolio/plantas", label: "Rótulo: banco de dados", defaultPt: "Banco de dados" },
  { key: "plantas.noLinkNotice", page: "portfolio/plantas", label: "Aviso: sem link de demo", multiline: true, defaultPt: "Projeto local, hardware físico montado em casa. Sem link de demo ou repositório público no momento." },
  { key: "plantas.demo.humidity", page: "portfolio/plantas", label: "Demo: rótulo umidade", defaultPt: "umidade" },
  { key: "plantas.demo.windowTitle", page: "portfolio/plantas", label: "Demo: título da janela", defaultPt: "Monitor de Plantas - dashboard" },
  { key: "plantas.demo.plant.fern", page: "portfolio/plantas", label: "Demo: nome da planta 1", defaultPt: "Samambaia" },
  { key: "plantas.demo.plant.succulent", page: "portfolio/plantas", label: "Demo: nome da planta 2", defaultPt: "Suculenta" },
  { key: "plantas.demo.plant.pothos", page: "portfolio/plantas", label: "Demo: nome da planta 3", defaultPt: "Jiboia" },
  { key: "plantas.demo.status.healthy", page: "portfolio/plantas", label: "Demo: status saudável", defaultPt: "saudável" },
  { key: "plantas.demo.status.attention", page: "portfolio/plantas", label: "Demo: status atenção", defaultPt: "atenção" },
  { key: "plantas.demo.status.dry", page: "portfolio/plantas", label: "Demo: status seca", defaultPt: "seca" },
  { key: "plantas.demo.watered.fern", page: "portfolio/plantas", label: "Demo: regada (samambaia)", defaultPt: "Regada há 3h" },
  { key: "plantas.demo.watered.succulent", page: "portfolio/plantas", label: "Demo: regada (suculenta)", defaultPt: "Regada há 9h" },
  { key: "plantas.demo.watered.pothos", page: "portfolio/plantas", label: "Demo: regada (jiboia)", defaultPt: "Regada há 1d" },
  { key: "plantas.overview.heading", page: "portfolio/plantas", label: "Visão Geral: título", defaultPt: "Visão Geral" },
  { key: "plantas.overview.body", page: "portfolio/plantas", label: "Visão Geral: texto", multiline: true, defaultPt: "O Monitor de Plantas cuida das plantas de casa quando não dá tempo: mede umidade da terra, temperatura, umidade do ar e luz, rega automaticamente quando necessário, tira fotos periódicas e avisa no celular se algo estiver errado, tudo isso sem depender da nuvem, rodando na própria rede Wi-Fi de casa. São três peças com deploy independente falando HTTP/JSON e um WebSocket cru na rede local: um ESP32 por vaso lê os sensores e aciona a bomba, um ESP32-CAM opcional fotografa as plantas, e um backend em Java (Javalin) guarda o histórico em SQLite, avalia as fotos e empurra atualizações ao vivo para o dashboard." },
  { key: "plantas.features.heading", page: "portfolio/plantas", label: "Recursos: título", defaultPt: "O que o sistema faz" },
  { key: "plantas.features.watering.title", page: "portfolio/plantas", label: "Recurso 1: título", defaultPt: "Rega automática por planta" },
  { key: "plantas.features.watering.description", page: "portfolio/plantas", label: "Recurso 1: descrição", multiline: true, defaultPt: "Cada ESP32 decide sozinho quando abrir o relé da bomba comparando a umidade do solo ao limiar configurado, com um tempo mínimo entre regas para não encharcar o vaso." },
  { key: "plantas.features.photos.title", page: "portfolio/plantas", label: "Recurso 2: título", defaultPt: "Fotos periódicas + saúde por cor" },
  { key: "plantas.features.photos.description", page: "portfolio/plantas", label: "Recurso 2: descrição", multiline: true, defaultPt: "Um ESP32-CAM opcional fotografa as plantas; um heurístico de cor (verde vs. amarelo/marrom) estima saúde, sem depender de nuvem nem de um modelo de ML." },
  { key: "plantas.features.push.title", page: "portfolio/plantas", label: "Recurso 3: título", defaultPt: "Notificação push mesmo com o app fechado" },
  { key: "plantas.features.push.description", page: "portfolio/plantas", label: "Recurso 3: descrição", multiline: true, defaultPt: "Web Push com VAPID avisa no celular quando a terra está seca há muito tempo, a bomba ligou e não resolveu, uma foto indica problema, ou um sensor parou de responder." },
  { key: "plantas.features.realtime.title", page: "portfolio/plantas", label: "Recurso 4: título", defaultPt: "Tempo real por WebSocket, sem nuvem" },
  { key: "plantas.features.realtime.description", page: "portfolio/plantas", label: "Recurso 4: descrição", multiline: true, defaultPt: "Dashboard PWA instalável no celular, atualizado ao vivo por um WebSocket próprio (sem Socket.IO), rodando inteiro na rede Wi-Fi de casa." },
  { key: "plantas.challenges.heading", page: "portfolio/plantas", label: "Desafio: título", defaultPt: "O Desafio" },
  { key: "plantas.challenges.item1", page: "portfolio/plantas", label: "Desafio 1", multiline: true, defaultPt: "Se o backend caísse (o computador desligou, por exemplo), as plantas não podiam ficar sem rega até alguém notar." },
  { key: "plantas.challenges.item2", page: "portfolio/plantas", label: "Desafio 2", multiline: true, defaultPt: "A ESP32-CAM tem pouquíssima RAM livre além do framebuffer da própria imagem, bufferizar a foto inteira antes de enviar arriscava estourar memória." },
  { key: "plantas.challenges.item3", page: "portfolio/plantas", label: "Desafio 3", multiline: true, defaultPt: "Timestamps chegavam em formatos diferentes dependendo da origem, o SQLite grava UTC sem 'Z', eventos de WebSocket vêm com 'Z', e isso já gerou um bug real: leituras ao vivo mostrando 'há NaN min'." },
  { key: "plantas.solutions.heading", page: "portfolio/plantas", label: "Solução: título", defaultPt: "A Solução" },
  { key: "plantas.solutions.item1", page: "portfolio/plantas", label: "Solução 1", multiline: true, defaultPt: "A lógica de rega automática mora inteira no firmware do ESP32, não no backend: ele decide sozinho quando abrir o relé comparando a leitura ao limiar guardado em memória. O dashboard só ajusta esse limiar remotamente; se o servidor cair, a planta continua sendo regada com o último valor configurado." },
  { key: "plantas.solutions.item2", page: "portfolio/plantas", label: "Solução 2", multiline: true, defaultPt: "O upload da foto é multipart, escrito em três chamadas HTTP separadas (cabeçalho, bytes JPEG crus, rodapé) em vez de concatenar tudo num buffer só, evitando dobrar o uso de RAM em cima do framebuffer da câmera." },
  { key: "plantas.solutions.item3", page: "portfolio/plantas", label: "Solução 3", multiline: true, defaultPt: "Todo timestamp que passa pelo frontend segue por um único helper (toUtcDate()) em vez de cada tela tratar o formato à sua maneira, a causa raiz do bug virou regra para qualquer código novo que toque em data." },
  { key: "plantas.architecture.heading", page: "portfolio/plantas", label: "Arquitetura: título", defaultPt: "Arquitetura do Sistema" },
  { key: "plantas.architecture.body", page: "portfolio/plantas", label: "Arquitetura: texto", multiline: true, defaultPt: "Três peças com deploy independente, sem fila de mensagens nem broker: o ESP32 de sensores fala HTTP direto com o backend, a ESP32-CAM sobe fotos por multipart, e o backend empurra tudo em tempo real para o dashboard por um WebSocket próprio." },
  { key: "plantas.architecture.diagram.esp32", page: "portfolio/plantas", label: "Diagrama: linha ESP32", defaultPt: "lê sensores por planta, decide e executa a rega sozinho" },
  { key: "plantas.architecture.diagram.cam", page: "portfolio/plantas", label: "Diagrama: linha ESP32-CAM", defaultPt: "fotos periódicas, upload multipart em streaming" },
  { key: "plantas.architecture.diagram.arrow1", page: "portfolio/plantas", label: "Diagrama: seta 1", defaultPt: "↓ HTTP POST leituras / foto" },
  { key: "plantas.architecture.diagram.backend", page: "portfolio/plantas", label: "Diagrama: linha backend", multiline: true, defaultPt: "guarda histórico em SQLite, avalia saúde por cor, agenda alerta de dispositivo offline" },
  { key: "plantas.architecture.diagram.arrow2", page: "portfolio/plantas", label: "Diagrama: seta 2", defaultPt: "↓ WebSocket + Web Push" },
  { key: "plantas.architecture.diagram.dashboard", page: "portfolio/plantas", label: "Diagrama: linha dashboard", multiline: true, defaultPt: "tempo real no navegador, instalável no celular, recebe push mesmo fechado" },
  { key: "plantas.limitations.heading", page: "portfolio/plantas", label: "Limitações: título", defaultPt: "Sem Nuvem, Sem Diagnóstico Mágico" },
  { key: "plantas.limitations.intro", page: "portfolio/plantas", label: "Limitações: introdução", defaultPt: "O sistema roda inteiro na rede de casa, de propósito, e é honesto sobre o que ainda não faz:" },
  { key: "plantas.limitations.item1", page: "portfolio/plantas", label: "Limitações: item 1", multiline: true, defaultPt: "Não identifica doenças específicas nem espécies de plantas, a avaliação da foto é um heurístico de cor (mais verde = melhor), não um diagnóstico." },
  { key: "plantas.limitations.item2", page: "portfolio/plantas", label: "Limitações: item 2", multiline: true, defaultPt: "Não funciona fora de casa \"pronto para uso\": acessar de fora da rede Wi-Fi exige configurar acesso remoto à parte." },
  { key: "plantas.limitations.item3Prefix", page: "portfolio/plantas", label: "Limitações: item 3 (antes do código)", defaultPt: "Sem ORM, sem pool de conexão: um único" },
  { key: "plantas.limitations.item3Suffix", page: "portfolio/plantas", label: "Limitações: item 3 (depois do código)", defaultPt: "JDBC direto, de propósito, para manter o backend simples de auditar." },
  { key: "plantas.limitations.item4", page: "portfolio/plantas", label: "Limitações: item 4", defaultPt: "Ainda sem suíte de testes ou linter configurado no backend." },

  // Portfolio: Ágora
  { key: "agora.title", page: "portfolio/agora", label: "Título", defaultPt: "Ágora" },
  { key: "agora.subtitle", page: "portfolio/agora", label: "Subtítulo", multiline: true, defaultPt: "Previsão de valorização de imóveis para investidores e fundos imobiliários: dados públicos e proprietários viram um painel de decisão de compra, venda e timing" },
  { key: "agora.date", page: "portfolio/agora", label: "Período", defaultPt: "2026 - Presente" },
  { key: "agora.role", page: "portfolio/agora", label: "Função (ficha técnica)", defaultPt: "Frontend Developer & Articulação de Equipe" },
  { key: "agora.status", page: "portfolio/agora", label: "Status (ficha técnica)", defaultPt: "Em validação (pitch e editais)" },
  { key: "agora.labels.role", page: "portfolio/agora", label: "Rótulo: função", defaultPt: "Função" },
  { key: "agora.labels.techStack", page: "portfolio/agora", label: "Título: tecnologias-alvo", defaultPt: "Tecnologias-Alvo do Roadmap" },
  { key: "agora.tags.statistics", page: "portfolio/agora", label: "Tecnologia 1", defaultPt: "Modelagem Estatística" },
  { key: "agora.tags.ml", page: "portfolio/agora", label: "Tecnologia 2", defaultPt: "Machine Learning" },
  { key: "agora.tags.backtesting", page: "portfolio/agora", label: "Tecnologia 3", defaultPt: "Backtesting" },
  { key: "agora.tags.geospatial", page: "portfolio/agora", label: "Tecnologia 4", defaultPt: "Dados Geoespaciais" },
  { key: "agora.tags.macro", page: "portfolio/agora", label: "Tecnologia 5", defaultPt: "Análise Macroeconômica" },
  { key: "agora.noLinkNotice", page: "portfolio/agora", label: "Aviso: sem link", multiline: true, defaultPt: "Projeto em fase de validação: participa de programas de inovação, com inscrição em editais. Ainda sem produto em produção nem link público." },
  { key: "agora.overview.heading", page: "portfolio/agora", label: "Visão Geral: título", defaultPt: "Visão Geral" },
  { key: "agora.overview.body", page: "portfolio/agora", label: "Visão Geral: texto", multiline: true, defaultPt: "O Ágora prevê a valorização e desvalorização de imóveis ao longo do tempo, cruzando dados públicos e macroeconômicos com dados proprietários de solo e topografia, e transformando a proximidade a pontos de referência (escolas, faculdades, obras públicas planejadas) em pontuação de valorização. É voltado a investidores e fundos imobiliários que precisam decidir compra, venda e timing com mais do que intuição de mercado. Sou responsável pelo frontend do produto e pela articulação da equipe multidisciplinar do projeto." },
  { key: "agora.features.heading", page: "portfolio/agora", label: "Recursos: título", defaultPt: "O que a plataforma propõe" },
  { key: "agora.features.prediction.title", page: "portfolio/agora", label: "Recurso 1: título", defaultPt: "Modelo de previsão de valorização" },
  { key: "agora.features.prediction.description", page: "portfolio/agora", label: "Recurso 1: descrição", multiline: true, defaultPt: "Núcleo estatístico e de machine learning que projeta a valorização de um imóvel ou região ao longo do tempo." },
  { key: "agora.features.data.title", page: "portfolio/agora", label: "Recurso 2: título", defaultPt: "Fontes de dados combinadas" },
  { key: "agora.features.data.description", page: "portfolio/agora", label: "Recurso 2: descrição", multiline: true, defaultPt: "Dados públicos e macroeconômicos combinados com dados proprietários de solo e topografia, mantidos rastreáveis por fonte." },
  { key: "agora.features.proximity.title", page: "portfolio/agora", label: "Recurso 3: título", defaultPt: "Pontuação por proximidade" },
  { key: "agora.features.proximity.description", page: "portfolio/agora", label: "Recurso 3: descrição", multiline: true, defaultPt: "Mede a proximidade do imóvel a escolas, faculdades e obras públicas planejadas, e converte isso em pontuação de valorização." },
  { key: "agora.features.scenarios.title", page: "portfolio/agora", label: "Recurso 4: título", defaultPt: "Simulação de cenários" },
  { key: "agora.features.scenarios.description", page: "portfolio/agora", label: "Recurso 4: descrição", multiline: true, defaultPt: "Compara cenários macroeconômicos e urbanos diferentes e o impacto de cada um na valorização projetada." },
  { key: "agora.challenges.heading", page: "portfolio/agora", label: "Desafio: título", defaultPt: "O Desafio" },
  { key: "agora.challenges.item1", page: "portfolio/agora", label: "Desafio 1", multiline: true, defaultPt: "Prever valorização de imóveis exige validar um modelo estatístico contra dados históricos reais, não apenas prometer precisão." },
  { key: "agora.challenges.item2", page: "portfolio/agora", label: "Desafio 2", multiline: true, defaultPt: "Cruzar dados públicos e macroeconômicos com dados proprietários de solo e topografia numa única previsão consistente, sem duplicar coleta nem perder rastreabilidade da fonte." },
  { key: "agora.challenges.item3", page: "portfolio/agora", label: "Desafio 3", multiline: true, defaultPt: "Definir a granularidade certa da previsão (região, bairro ou imóvel individual) sem prometer um nível de precisão que o volume de dados disponível ainda não sustenta." },
  { key: "agora.solutions.heading", page: "portfolio/agora", label: "Solução: título", defaultPt: "A Solução" },
  { key: "agora.solutions.item1", page: "portfolio/agora", label: "Solução 1", multiline: true, defaultPt: "Metodologia de validação por backtesting temporal: treinar o modelo só com dado histórico até um corte e comparar a valorização projetada contra o que de fato aconteceu em índices públicos de mercado." },
  { key: "agora.solutions.item2", page: "portfolio/agora", label: "Solução 2", multiline: true, defaultPt: "Pipeline de dados que mantém separadas as fontes públicas/macroeconômicas e as proprietárias, permitindo auditar de onde cada variável do modelo veio." },
  { key: "agora.solutions.item3", page: "portfolio/agora", label: "Solução 3", multiline: true, defaultPt: "Granularidade inicial definida por região e bairro, não por imóvel individual, até haver volume de transação suficiente por endereço para sustentar uma previsão estatisticamente confiável." },

  // Portfolio: EngScan
  { key: "engscan.title", page: "portfolio/engscan", label: "Título", defaultPt: "EngScan" },
  { key: "engscan.subtitle", page: "portfolio/engscan", label: "Subtítulo", defaultPt: "Solução baseada em microsserviços para análise de imagens e laudos automáticos" },
  { key: "engscan.date", page: "portfolio/engscan", label: "Período", defaultPt: "2024 - 2026" },
  { key: "engscan.role", page: "portfolio/engscan", label: "Função (ficha técnica)", defaultPt: "Lead Full-stack Developer & ML Engineer" },
  { key: "engscan.status", page: "portfolio/engscan", label: "Status (ficha técnica)", defaultPt: "Em Produção" },
  { key: "engscan.labels.role", page: "portfolio/engscan", label: "Rótulo: função", defaultPt: "Função" },
  { key: "engscan.labels.year", page: "portfolio/engscan", label: "Rótulo: ano", defaultPt: "Ano" },
  { key: "engscan.labels.techStack", page: "portfolio/engscan", label: "Título: stack tecnológica", defaultPt: "Stack Tecnológica" },
  { key: "engscan.overview.heading", page: "portfolio/engscan", label: "Visão Geral: título", defaultPt: "Visão Geral" },
  { key: "engscan.overview.body", page: "portfolio/engscan", label: "Visão Geral: texto", multiline: true, defaultPt: "EngScan é uma solução baseada em microsserviços para análise de imagens e geração automática de laudos. Interface em Angular, APIs e lógica de negócio em NestJS, biblioteca Python para composição de relatórios e modelos de machine learning (rede neural e CNN) que realizam diagnóstico automatizado a partir dos dados e imagens." },
  { key: "engscan.challenges.heading", page: "portfolio/engscan", label: "Desafio: título", defaultPt: "O Desafio" },
  { key: "engscan.challenges.item1", page: "portfolio/engscan", label: "Desafio 1", defaultPt: "Processamento de imagens de alta resolução causava gargalos na API principal." },
  { key: "engscan.challenges.item2", page: "portfolio/engscan", label: "Desafio 2", defaultPt: "Necessidade de isolar o ambiente Python (ML) do núcleo da aplicação em Node.js." },
  { key: "engscan.challenges.item3", page: "portfolio/engscan", label: "Desafio 3", defaultPt: "Gerar PDFs complexos com layout técnico exigido pelas normas ABNT." },
  { key: "engscan.solutions.heading", page: "portfolio/engscan", label: "Solução: título", defaultPt: "A Solução" },
  { key: "engscan.solutions.item1", page: "portfolio/engscan", label: "Solução 1", defaultPt: "Arquitetura de microsserviços orientada a eventos usando RabbitMQ para comunicação assíncrona." },
  { key: "engscan.solutions.item2", page: "portfolio/engscan", label: "Solução 2", defaultPt: "Serviço dedicado de GPU em Python para rodar os modelos CNN (Redes Neurais Convolucionais)." },
  { key: "engscan.solutions.item3", page: "portfolio/engscan", label: "Solução 3", defaultPt: "Fila de processamento em background (BullMQ) para geração de relatórios sem travar a interface do usuário." },
  { key: "engscan.architecture.heading", page: "portfolio/engscan", label: "Arquitetura: título", defaultPt: "Arquitetura do Sistema" },
  { key: "engscan.architecture.body", page: "portfolio/engscan", label: "Arquitetura: texto", multiline: true, defaultPt: "O sistema utiliza uma abordagem desacoplada. O Frontend em Angular comunica-se com um Gateway API em NestJS. Processos pesados (IA e Geração de PDF) são delegados a filas (RabbitMQ) e consumidos por workers especializados em Python." },
  { key: "engscan.architecture.placeholder", page: "portfolio/engscan", label: "Placeholder do diagrama", defaultPt: "[Diagrama de Arquitetura de Microsserviços: Angular → NestJS Gateway → RabbitMQ → Python Workers]" },
  { key: "engscan.links.demo", page: "portfolio/engscan", label: "Botão: acessar demo online", defaultPt: "Acessar Demo Online" },
  { key: "engscan.links.github", page: "portfolio/engscan", label: "Botão: mais sobre", defaultPt: "Mais Sobre" },

  // Portfolio: Flugo
  { key: "flugo.title", page: "portfolio/flugo", label: "Título", defaultPt: "Flugo" },
  { key: "flugo.subtitle", page: "portfolio/flugo", label: "Subtítulo", defaultPt: "Sistema inteligente de onboarding e cadastro de colaboradores" },
  { key: "flugo.date", page: "portfolio/flugo", label: "Período", defaultPt: "2026" },
  { key: "flugo.role", page: "portfolio/flugo", label: "Função (ficha técnica)", defaultPt: "Full-stack Developer" },
  { key: "flugo.status", page: "portfolio/flugo", label: "Status (ficha técnica)", defaultPt: "Finalizado" },
  { key: "flugo.labels.role", page: "portfolio/flugo", label: "Rótulo: função", defaultPt: "Papel" },
  { key: "flugo.labels.year", page: "portfolio/flugo", label: "Rótulo: ano", defaultPt: "Ano" },
  { key: "flugo.labels.techStack", page: "portfolio/flugo", label: "Título: tecnologias utilizadas", defaultPt: "Tecnologias Utilizadas" },
  { key: "flugo.overview.heading", page: "portfolio/flugo", label: "Sobre o Projeto: título", defaultPt: "Sobre o Projeto" },
  { key: "flugo.overview.body", page: "portfolio/flugo", label: "Sobre o Projeto: texto", multiline: true, defaultPt: "O Flugo é uma plataforma centralizada para o gerenciamento do fluxo de entrada de novos talentos. O projeto foca em oferecer um formulário de cadastro dinâmico, garantindo que a coleta de dados sensíveis e documentos dos colaboradores seja feita de forma segura, validada e com uma experiência de usuário fluida (UX), eliminando processos manuais em papel." },
  { key: "flugo.challenges.heading", page: "portfolio/flugo", label: "Desafio: título", defaultPt: "O Desafio" },
  { key: "flugo.challenges.item1", page: "portfolio/flugo", label: "Desafio 1", defaultPt: "Validar fluxos complexos de dados (CPF, CEP, PIS) em tempo real sem perder performance." },
  { key: "flugo.challenges.item2", page: "portfolio/flugo", label: "Desafio 2", defaultPt: "Gerenciar o upload e armazenamento seguro de documentos digitalizados." },
  { key: "flugo.challenges.item3", page: "portfolio/flugo", label: "Desafio 3", defaultPt: "Criar uma interface responsiva que guie o usuário por múltiplas etapas sem causar fadiga." },
  { key: "flugo.solutions.heading", page: "portfolio/flugo", label: "Solução: título", defaultPt: "A Solução" },
  { key: "flugo.solutions.item1", page: "portfolio/flugo", label: "Solução 1", defaultPt: "Implementação de formulários multi-step com persistência de estado local para evitar perda de dados." },
  { key: "flugo.solutions.item2", page: "portfolio/flugo", label: "Solução 2", defaultPt: "Validação rigorosa de esquemas utilizando Zod integrada ao React Hook Form." },
  { key: "flugo.solutions.item3", page: "portfolio/flugo", label: "Solução 3", defaultPt: "Integração com APIs externas (como ViaCEP) para preenchimento automático de endereços e redução de erros digitais." },
  { key: "flugo.architecture.heading", page: "portfolio/flugo", label: "Arquitetura: título", defaultPt: "Arquitetura de Dados" },
  { key: "flugo.architecture.body", page: "portfolio/flugo", label: "Arquitetura: texto", multiline: true, defaultPt: "O formulário foi construído utilizando uma arquitetura orientada a estados, onde cada etapa é validada de forma independente antes de permitir o avanço. Os dados são processados por um servidor Next.js (API Routes) e persistidos de forma segura no banco de dados através do Prisma ORM." },
  { key: "flugo.architecture.placeholder", page: "portfolio/flugo", label: "Placeholder do diagrama", defaultPt: "[Diagrama de Fluxo: Usuário → React Hook Form (Zod) → Next.js API → Prisma → PostgreSQL]" },
  { key: "flugo.links.demo", page: "portfolio/flugo", label: "Botão: ver formulário vivo", defaultPt: "Ver Formulário Vivo" },
  { key: "flugo.links.github", page: "portfolio/flugo", label: "Botão: repositório", defaultPt: "Repositório" },

  // Contato
  { key: "contato.info.email.label", page: "contato", label: "Card Email: rótulo", defaultPt: "Email" },
  { key: "contato.info.email.description", page: "contato", label: "Card Email: descrição", defaultPt: "Respondo em até 24 horas" },
  { key: "contato.info.linkedin.label", page: "contato", label: "Card LinkedIn: rótulo", defaultPt: "LinkedIn" },
  { key: "contato.info.linkedin.description", page: "contato", label: "Card LinkedIn: descrição", defaultPt: "Respondo em até 42 horas" },
  { key: "contato.info.github.label", page: "contato", label: "Card GitHub: rótulo", defaultPt: "GitHub" },
  { key: "contato.info.github.description", page: "contato", label: "Card GitHub: descrição", defaultPt: "Confira meus projetos" },
  { key: "contato.info.location.label", page: "contato", label: "Card Localização: rótulo", defaultPt: "Localização" },
  { key: "contato.info.location.description", page: "contato", label: "Card Localização: descrição", defaultPt: "Disponível para trabalho remoto" },
  { key: "contato.form.heading", page: "contato", label: "Formulário: título", defaultPt: "Envie uma mensagem" },
  { key: "contato.form.intro", page: "contato", label: "Formulário: introdução", defaultPt: "Preencha o formulário abaixo e eu retorno o quanto antes." },
  { key: "contato.form.name", page: "contato", label: "Campo: nome", defaultPt: "Nome *" },
  { key: "contato.form.email", page: "contato", label: "Campo: email", defaultPt: "Email *" },
  { key: "contato.form.subject", page: "contato", label: "Campo: assunto", defaultPt: "Assunto" },
  { key: "contato.form.message", page: "contato", label: "Campo: mensagem", defaultPt: "Mensagem *" },
  { key: "contato.form.success", page: "contato", label: "Mensagem de sucesso", defaultPt: "Mensagem enviada com sucesso!" },
  { key: "contato.form.genericError", page: "contato", label: "Mensagem de erro genérica", defaultPt: "Não foi possível enviar sua mensagem." },
  { key: "contato.form.submit", page: "contato", label: "Botão: enviar mensagem", defaultPt: "Enviar mensagem" },

  // Currículos
  { key: "curriculos.title", page: "curriculos", label: "Título da página", defaultPt: "Currículos" },
  { key: "curriculos.intro", page: "curriculos", label: "Texto de introdução", defaultPt: "Catálogo com as versões do meu currículo. Escolha uma, leia direto no navegador ou baixe o PDF." },
  { key: "curriculos.empty", page: "curriculos", label: "Mensagem: nenhum currículo", defaultPt: "Nenhum currículo cadastrado ainda." },
  { key: "curriculos.updatedPrefix", page: "curriculos", label: "Prefixo: atualizado em", defaultPt: "Atualizado em" },
  { key: "curriculos.view", page: "curriculos", label: "Botão: ver", defaultPt: "Ver" },
  { key: "curriculos.download", page: "curriculos", label: "Botão: baixar", defaultPt: "Baixar" },
  { key: "curriculos.geral.idioma", page: "curriculos", label: "Currículo Geral: idioma", defaultPt: "Português" },
  { key: "curriculos.geral.titulo", page: "curriculos", label: "Currículo Geral: título", defaultPt: "Currículo - Geral" },
  { key: "curriculos.geral.descricao", page: "curriculos", label: "Currículo Geral: descrição", defaultPt: "Visão geral de experiência como engenheiro de software e pesquisador em IA." },
  { key: "curriculos.geral.atualizado", page: "curriculos", label: "Currículo Geral: data de atualização", defaultPt: "Setembro de 2026" },

  // 404
  { key: "notFound.title", page: "notFound", label: "Título", defaultPt: "Página Não Encontrada" },
  { key: "notFound.description", page: "notFound", label: "Descrição", defaultPt: "A página que você está procurando não existe." },
  { key: "notFound.backHome", page: "notFound", label: "Botão: voltar para a página inicial", defaultPt: "Voltar para a Página Inicial" },

  // Portfolio (índice)
  { key: "portfolio.loading", page: "portfolio", label: "Mensagem de carregamento", defaultPt: "Carregando portfólio..." },
  { key: "portfolio.title", page: "portfolio", label: "Título da página", defaultPt: "Portfolio" },
  { key: "portfolio.intro", page: "portfolio", label: "Texto de introdução", multiline: true, defaultPt: "Uma seleção dos meus projetos como programador e pesquisador, demonstrando a aplicação prática de tecnologias modernas e contribuições científicas e acadêmicas." },
  { key: "portfolio.programmer.heading", page: "portfolio", label: "Seção Programador: título", defaultPt: "Programador" },
  { key: "portfolio.researcher.heading", page: "portfolio", label: "Seção Pesquisador: título", defaultPt: "Pesquisador" },
  { key: "portfolio.button.details", page: "portfolio", label: "Botão: detalhes", defaultPt: "Detalhes" },
];

export const CONTENT_KEYS_BY_KEY: Record<string, ContentKeyDef> = Object.fromEntries(
  CONTENT_KEYS.map((entry) => [entry.key, entry])
);

export const CONTENT_PAGES: string[] = Array.from(new Set(CONTENT_KEYS.map((entry) => entry.page)));

export function defaultText(key: string, locale: string): string | undefined {
  return (locale === "en" ? DEFAULT_EN[key] : undefined) ?? CONTENT_KEYS_BY_KEY[key]?.defaultPt;
}
